# -*- coding: utf-8 -*-
"""gearbox_failure_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11JKKK2KpE1ilcnHaJ22_FpXlig1p5-ie
"""

import streamlit as st
import pandas as pd
import joblib

# Load trained model
model = joblib.load("gearbox_failure_model.pkl")

# Title
st.title("Gearbox Failure Prediction System")

st.write("Enter gearbox sensor values to predict whether the gearbox will fail or not.")

# User Inputs
load = st.number_input("Load %")
temperature = st.number_input("Temperature (C)")
vibration = st.number_input("Vibration (mm/s)")
oil_level = st.number_input("Oil Level %")

# Create dataframe
input_data = pd.DataFrame({
    "Load_%":[load],
    "Temperature_C":[temperature],
    "Vibration_mm_s":[vibration],
    "Oil_Level_%":[oil_level]
})

# Prediction
if st.button("Predict"):

    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error("⚠️ Gearbox Failure Predicted")
    else:
        st.success("✅ Gearbox is Working Normally")